apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-l2sm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
      annotations:
        k8s.v1.cni.cncf.io/networks: my-second-network#sriov-net1
    spec:
      containers: 
      - name: pong
        command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
        image: alpine:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        resources:
          requests:
            intel.com/intel_sriov_netdevice: '1'
          limits:
            intel.com/intel_sriov_netdevice: '1'
      # Use this parameter if you want to place the pod in a specific node
      # nodeName: rex 
