apiVersion: apps/v1
kind: Deployment
metadata:
  name: l2sm-operator-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      l2sm-component: l2sm-opt
  template:
    metadata:
      labels:
        l2sm-component: l2sm-opt
    spec:
      serviceAccountName: l2sm-operator
      containers:
      - image: l2sm-dev:dev
        name: l2sm-opt-pod
        resources:
          limits:
            cpu: "500m"
            memory: "128Mi"
          requests:
            cpu: "250m"
            memory: "64Mi"
        env:
          - name: CONTROLLER
            value: http://onos:rocks@10.68.48.9:8181
      - image: mysql/mysql-server:latest
        imagePullPolicy: IfNotPresent
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: L2SM
          - name: MYSQL_USER
            value: l2sm
          - name: MYSQL_PASSWORD
            value: l2sm;
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: "1"
            memory: "1G"
          requests:
            cpu: "500m"
            memory: "512M"
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule

--- 

apiVersion: v1
kind: Service
metadata:
  name: l2sm-opt-service
spec:
  selector:
    l2sm-component: l2sm-opt
  ports:
    - port: 3306
      targetPort: 3306
